### ISSUE TITLE
crashes on psvita when playing pure tracks "wipeout pulse fx350"

### ISSUE THREAD

**Issue by SirSoloPlayer** [NR74W/WipEout-Mods#1]
adrealine freezes whenever i start a pure track or even when playing it .. i dont know why tho

**Comment by NR74W** [comment]
This mod can only be played on PPSSPP, unfortunately. From the README:
> The unofficial tracks are not well supported, causing Invalid Memory Access errors. Only a few tracks can be loaded and all the others crashes the game.
> It can be bypassed by enabling "Ignore illegal reads/writes" in PPSSPP, the mod is only compatible with PPSSPP.
> Sometimes the game can still crash after initializing / exiting a race.
