### ISSUE TITLE
2 tracks are broken

### ISSUE THREAD

**Issue by Light37M** [NR74W/WipEout-Mods#12]
Dear

I discovered a bug in 2 of the tracks
Altima VII
Odessa Keys

Both give issue trying to complete the race. They respawn the vehicles when crossing the bridge.

Can you check? Many thanks.

**Comment by NR74W** [comment]
The issue in question is the broken track rendering on Altima VII and Porto Kora, only in the "E" version of WipEout Pulse: Future Edition. A warning screen with the issues present only in this specific version is displayed right after the Title Screen/Memory Stick Screen.

It should be noted that the normal version of Future Edition is "bug-free", as much as the original game was.
E stands for "Experimental": unstable and/or unsuitable to be present in the main release.
The experimental features (which are just the tracks from WipEout Pure) are not part of the base mod.

Despite all the attempts to make these two tracks work in over 3 years, it never succeeded. It is possibly an issue at the start or end of the wo_track node, or perhaps something else entirely.
Only someone else with the necessary skills/knowledge could probably find a way to fix them, but it may never happen.

**Comment by Light37M** [comment]
ok noted, thanks for your swift feedback! and many thanks for you great work! Best wishes and a great new year!
