### ISSUE TITLE
60FPS unlock hitches/stutters on real hardware - WipEout Pure: Special Edition v5.0

### ISSUE THREAD

**Issue by isolatedinsomnia** [NR74W/WipEout-Mods#2]
On PSP 3000/Brite, 333/166mhz clock, Time Trial and Zone mode will jump between 30 and 60fps modes intermittedly, causing momentary stutters in gameplay; this seems to be the behavior also exhibited by the 60fps cheat released for the UCES-00001 version of Pure. 

Is there any chance this feature could be made optional, or a ["revert" cheat](https://pastebin.com/raw/vmyyx7B1) made available for the new WPSE-02197 game ID?

_(v5.0 looks like it was no small undertaking, all the new content is fantastic! Thank you for your hard work!)_

**Comment by NR74W** [comment]
Thanks!
The addresses are identical, so the same codes can be used.
```
_S WPSE-02197
_G WipEout Pure: Special Edition
_C1 Restore original framelimit (30FPS Menu/Time Trial/Zone/Free Play)
_L 0x2006509C 0x1480FFFB
```

**Comment by isolatedinsomnia** [comment]
Ah, that would do it, works like a charm. Thank you!
