### ISSUE TITLE
Feature Request - Ship Stat Changes and Zone Ship Description - WipEout Pure: Special Edition

### ISSUE THREAD

**Issue by PatrickE-626** [NR74W/WipEout-Mods#6]
Would it be possible to make an optional DLC pack that not only changes the stats of various ships, but also to make the description for the Zone ship more detailed? I feel like some of the teams from the base game, as well as some of the promotional DLC ships aren't up to par with the likes of Tigron, Van-Uber, Icaras and Goteki 45. It's okay if this request is not possible on your end to do.

I've attached a Notepad file of what I have suggested for the stat changes and the Zone ship description.
[Wipeout Pure - Ship Stat Changes V3.txt](https://github.com/user-attachments/files/16842651/Wipeout.Pure.-.Ship.Stat.Changes.V3.txt)

**Comment by ThatOneBonk** [comment]
Note that there is much more to ship stats than just the numbers you see in the main menu. These stats are called frontend stats - the ones that actually define how a ship flies are much more complex. Changing ship stats also delves into the balancing territory, which is something to consider since one could play online with these stat changes.
As a side note, you used the wrong "it's" in the Zone ship description :p
All of this is something that should be straightforward to implement, however.

**Comment by PatrickE-626** [comment]
I do agree with what you brought up in terms of balance for the online modes. Maybe if it's too much of a concern for online balance regarding the stat changes, disabling the online modes could be serve as a compromise for the ship statistic changes. 

And side note taken regarding the Zone ship description. Come to think of it, the WIRE05 ship description seems too basic. I'll see if I give a better WIRE05 ship description later on.

**Comment by PatrickE-626** [comment]
Updated the Notepad file again with the following changes:

- Slight change for the WIRE05 ship description.
- Added detailed ship descriptions for both "PUMA 1" and "PUMA 2".
- Altered the stat changes for the Stealth craft from '+1 Speed and +2 Thrust' to '+1 Speed and +2 Shield'. Previous statistic changes for Stealth would have made the ship very similar to Icaras.

**Comment by NR74W** [comment]
Sorry for the late reply, I was quite busy with WipEout Pulse.
FE stats only vaguely reflect the ships real stats. This should give you an idea how the game handles them:
![handlingstats](https://github.com/user-attachments/assets/5c94e640-f3c8-455b-95de-b7db8087fa03)
There are 21 ships to be modified and for each of the 5 speed classes, this would take a lot of time that I don't have.
In the past, I did take some liberties for the mods but it always screwed things up in the end. WPSE v5 and WPFE v5 were made to fix all these long-standing issues, taking a step in the right direction.
It's certainly for the best to not alter any stats (except to fix bugs like the Triakis glitch).

Here is the DLC with the new descriptions and ship stats you provided. Only the menu stats were altered so it's only a cosmetic change, I hope it's okay:

`Type-1 Pack` [WPSE02197DTYPE1.zip](https://github.com/user-attachments/files/16936780/WPSE02197DTYPE1.zip)

**Comment by PatrickE-626** [comment]
To NR74W,

Regarding the DLC pack with the menu stat changes and the new ship descriptions, that's definitely alright by me. So much thanks for your efforts. I can understand your reasons for not altering the actual ship stats. 

If it's completely okay with you, would it be possible for me to acquire the ship stat files and have a go at experimenting with the real ship statistics myself? I tried using the "wadutil" tool a few times to extract the files from WPSE v5, but even then I couldn't get the statistic data for all of the 21 ships, despite the repeated attempts.

**Comment by PatrickE-626** [comment]
Although this is only a WIP, I've listed a NotePad file with my proposed changes for the actual ship statistics and not the frontend stats as seen from the menu interface. Keep in mind that the detail changes may be subject to change, since I'm still missing a couple of ship stat files from the total of 21 ships (excluding the Zone ship variant solely used for Zone mode).

[Wipeout Pure - Real Ship Statistics (WIP).txt](https://github.com/user-attachments/files/16977466/Wipeout.Pure.-.Real.Ship.Statistics.WIP.txt)

**Comment by NR74W** [comment]
wadutil recovers the file names (stored as hash in the WAD) using the filenames.txt file.
Here is the updated [filenames.txt](https://github.com/user-attachments/files/16985375/filenames.txt) for wadutil with all file names from WPSE, good luck.

**Comment by PatrickE-626** [comment]
> wadutil recovers the file names (stored as hash in the WAD) using the filenames.txt file. Here is the updated [filenames.txt](https://github.com/user-attachments/files/16985375/filenames.txt) for wadutil with all file names from WPSE, good luck.

Thanks for the updated "filenames.txt"; just gave "wadutil" another try and all the filenames had been extracted successfully. Now I should be able to continue where I left off from experimenting with the actual ship stats. It may take a couple of days to finalize, but once done I'll sent the modified XMLs for the actual stats for all 27 ships and an updated changelog to reflect on the changes that I have implemented.

**Comment by PatrickE-626** [comment]
I have finished with modifying the files for the ship statistics, and as such I've included the necessary XML files along with two Notepad files containing a changelog of what's been modified from the real ship stats as well as the frontend stats and detailed descriptions for certain ships from previously. I made sure to validate the XML handling files for all 27 ships.

As an optional alternative, I've also included a separate XML file for the Triakis ship for the occasion if the deceleration glitch gets fixed in a future update for WPSE.
[WipEout Pure Special Edition - Type 1 Pack - Stats Changes.zip](https://github.com/user-attachments/files/16993834/WipEout.Pure.Special.Edition.-.Type.1.Pack.-.Stats.Changes.zip)

**Comment by NR74W** [comment]
The Triakis stats was already fixed in v3.0, two years ago. The retail game originally used some deprecated values from early prototypes for Triakis and some other ships.
I won't distribute it as DLC, instead you can add the [contents](https://www.mediafire.com/file/c7whx4mp4ez72k3/Type-A.zip/file) in the ISO using UMDGen.
If it satisfies your request, please close the issue.

**Comment by PatrickE-626** [comment]
Yes, that does certainly resolve the feature request. So much thanks for that!

**Comment by PatrickE-626** [comment]
Sorry that I have to reopen this issue again, but with the latest WPSE update I have attempted to include the modifications for both the real and frontend ship stats, as well as the changed ship descriptions and a few changes to the weapons as well. I've also moved the "Type 1 DLC" away from my SAVEDATA folder since I've added an alternate Gokeki 45 ship description, changed the Assegai frontend stats, and tweaked a lot of the actual ship stats, all of which is noted via changelogs.

I tried adding the changes via UMDGen, and whilst the real ship statistics and changed weapon data are working as intended, the game does not display the altered ship descriptions / frontend stats, instead it displays the default values and descriptions. I do not want you to distribute this as DLC, but is it possible to take another look and see if we can get the alternate descriptions and frontend stats to display correctly via FEData.wad?

It's okay if you can't help on this occasion.

[WipEout Pure Special Edition - Type 1 Pack - Stats Changes - V2.zip](https://github.com/user-attachments/files/17128712/WipEout.Pure.Special.Edition.-.Type.1.Pack.-.Stats.Changes.-.V2.zip)

**Comment by NR74W** [comment]
Here is the [updated](https://www.mediafire.com/file/b1u84ueqt257zl9/Type-A_V2.zip/file) file.

**Comment by PatrickE-626** [comment]
![WPSE02197_00001](https://github.com/user-attachments/assets/769f422e-e2ff-41ef-81f7-eb3011e01b23)

Just checked, I've noticed that the coloured bars for the speed and handling stars are mismatched for the Assegai team. Everything else regarding the ship descriptions and frontend stats for the other ships are displaying correctly as intended.

**Comment by NR74W** [comment]
Here is the [update](https://www.mediafire.com/file/0dk8mu0xr7lnuw6/Type-A_V3.zip/file) for V3.

**Comment by PatrickE-626** [comment]
There we go, now everything is in order. Thanks a lot!

It's safe to say that I can close this issue from this point on.

**Comment by PatrickE-626** [comment]
Although the music replacement issue from earlier has been resolved, the ship stats/description revision isn't fully working as I initially thought. Likewise this the very last revision and I'm not doing anymore beyond this one. I've altered the descriptions for the Triakis and Tigron teams, as well as altering the stats for Tigron to not make their ship function too similar to Auricom. I've also wanted to make the Zone ship stand out from the other ships by having the highest turbo amount, though I'm not sure what the turbo values contributes to on a technical aspect.

I'll say this again, it's completely okay if you are unable to help this time.


[WipEout Pure Special Edition - Type 1 Pack - Stats Changes - V3.zip](https://github.com/user-attachments/files/17610168/WipEout.Pure.Special.Edition.-.Type.1.Pack.-.Stats.Changes.-.V3.zip)

**Comment by NR74W** [comment]
Some folders in the .zip you uploaded have incorrect filename case again, preventing some files from being read.
It's now [fixed](https://www.mediafire.com/file/gzdhpugzhx4xbln/Type-1_Final.zip/file).

**Comment by PatrickE-626** [comment]
Alright, much thanks for that; I've removed the FEData.wad and placed the changed files onto the corresponding directory, and and the changes are working as intended. 

I can finally put this issue to a close now, as this is the last stat change revision. So again, thanks for helping me out!
