### ISSUE TITLE
Feature Request - Music Replacement and Transcendence Tournament - WipEout Pure: Special Edition

### ISSUE THREAD

**Issue by PatrickE-626** [NR74W/WipEout-Mods#9]
With the latest update for WPSE, I have two questions that spring to mind:

1) Is it possible to replace some of the music tracks that's used for the race modes, primarily the music featured in the Pure Urban packs?  I am not asking for the music replacements to be distributed as DLC, but I was wondering if it's possible to get some assistance with this, because I've tried implementing the music replacements onto the FEData.wad via UMDGEN, but every time I do so the game immediately crashes whenever I attempted to open the game ISO with the music replacements.

2) As with version 5.3 of WPSE, I've found that the monstrous 16-race Transcendence tournament was recently removed. Are there any reasons as to why the Transcendence tournament had to be excluded from the latest WPSE update?

**Comment by NR74W** [comment]
1. Currently, it's impossible to create custom DLC with big files (any .at3 or track .vex).
A full tutorial for music replacement is already available in the MEGA repository.
The content has to be added in the .iso directly.

3. The Transcendence tournament was not "removed", simply moved to the "Zone Pack".
This is unofficial content, it does not belong in the mod so it's made optional instead.
With the Zone Pack installed, the Zone League and Transcendence/Reminiscence tournaments are added.

**Comment by PatrickE-626** [comment]
1. I have followed the instructions from the music replacement tutorial provided, and while my attempts this time didn't crash the game, the custom music replacements aren't playing as intended, instead the default music provided is still being played. I've placed the music replacements under the "USRDIR/Data/Music" directory, so I don't know why the default music is still be prioritized. Mind you, the music replacements are for some of the Pure Urban tracks and Exit 17.

I've listed a link to the music replacements in question, if you want to have a look at, alongside one last revision of stat changes for the ships (both real and frontend).

2. Alright, thanks for clarifying that. I'll have a try with the Zone Pack then.


https://www.mediafire.com/file/wyh11l97i0slraa/WipEout_Pure_Special_Edition_-_Type_1_Pack_-_Stats_and_Music_Changes_-_V3.zip/file

**Comment by NR74W** [comment]
The folders in the Data.zip I provided for the tutorial had both lowercase and uppercase characters for a good reason, this is because the filenames are case-sensitive. The .zip file you sent has altered filenames (lowercase for Data and all the Music folders).
If any folder or file does not have the exact name the game expects, it won't be loaded.

Example:
- `data/Music/exit15` -> INCORRECT
- `Data/Music/Exit15` -> CORRECT

This information was missing in the text file, it's now added along with all filenames.

**Comment by PatrickE-626** [comment]
Redone the process and adjusted the filenames, and success! The custom music is now working as intended, thanks again!

I should be able to handle the ship stats revision by myself from this point on, so I'll close this issue now.
